#!/bin/bash

cd `dirname $0`
SCRIPT_DIR=`pwd`
FILES_DIR="$SCRIPT_DIR/files"
BACKUP_DIR="$SCRIPT_DIR/backup"

echo -n "Linking Files..."
ls -A "$FILES_DIR" |
while read file; do
    fname=`basename $file`
    # Check if there's already a file of that name, not pointing at the repository
    if [[ -e "$HOME/$fname" && ! -L "$HOME/$fname" ]]; then
        mkdir -p "$BACKUP_DIR/$dname"
        mv "$HOME/$fname" "$BACKUP_DIR/$fname"
    fi
    ln -s "$FILES_DIR/$fname" "$HOME/$fname"
done

echo "done"

if [[ -e "$BACKUP_DIR" ]]; then
    echo -n "Copying local files to repository..."
    ls -A "$BACKUP_DIR" |
    while read file; do
        fname=`basename $file`
        rm -rf "$FILES_DIR/$fname"
        cp -r "$BACKUP_DIR/$fname" "$FILES_DIR/$fname"
    done

    rm -rf "$BACKUP_DIR"
    echo "done"
fi
