#!/bin/bash

cd `dirname $0`
SCRIPT_DIR=`pwd`
FILES_DIR="$SCRIPT_DIR/files"
BACKUP_DIR="$SCRIPT_DIR/backup"

find $BACKUP_DIR -type f |
while read file; do
    fname=${file#$BACKUP_DIR/}
    cp "$BACKUP_DIR/$fname" "$FILES_DIR/$fname"
done
